# Generated by Django 4.1.3 on 2022-11-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articleContent',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleTitle',
            new_name='article_title',
        ),
    ]
