# Generated by Django 4.1.3 on 2022-11-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0006_user_delete_author_alter_article_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medium.user'),
        ),
    ]
