# Generated by Django 4.1.3 on 2022-11-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0011_alter_article_summary_author_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.TextField(blank=True, help_text='Enter a brief description of your self', max_length=1000),
        ),
    ]
