# Generated by Django 4.1.3 on 2022-11-16 03:43

import django.core.files.storage
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0014_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tutorial_Video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default='settings.MEDIA_ROOT/default_photo.jpg', storage=django.core.files.storage.FileSystemStorage(location='/Users/piotrrutkowski/PycharmProjects/djangoProject1/media'), upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
