# Generated by Django 4.1.3 on 2022-11-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0016_rename_tutorial_video_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
