# Generated by Django 4.1.3 on 2022-11-16 05:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0017_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='settings.MEDIA_ROOT/default_photo.jpg', storage=django.core.files.storage.FileSystemStorage(location='/Users/piotrrutkowski/PycharmProjects/djangoProject1/media'), upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
